### ISSUE TITLE
Insecure registry with nossl not working. 

### ISSUE THREAD

**Issue by qubusp** [keel-hq/keel#331] opened 2019-01-08 13:26 UTC
I'm getting the following error: 

```
time="2019-01-08T13:24:24Z" level=error msg="trigger.poll.manager: got error(-s) while watching images" error="encountered errors while adding images: Get https://registry.example.com:9000/v2/dashboard-ui/dashboard-ui/manifests/dev.11: http: server gave HTTP response to HTTPS client"
```
My K8s has access to the insecure registry. I think the issue is somewhere else.

**Comment by rusenask** [comment] 2019-01-09 15:40
yeah, seems like the client wants HTTPS. I think the problem is somewhere here https://github.com/keel-hq/keel/blob/master/registry/registry.go or maybe in the client itself. Is there any chance you can enable TLS for the registry?

**Comment by qubusp** [comment] 2019-01-09 16:06
Not really, it's internal domain,  and I don't have a wildcard certificate for it unfortunately.

**Comment by rusenask** [comment] 2019-02-06 21:39
Hi @qubusp, do you specify http:// in the deployment manifest or k8s detects it on its own?

**Comment by rusenask** [comment] 2019-02-06 22:27
Fixed with https://github.com/keel-hq/keel/pull/344

**Closed by rusenask** 2019-02-06 22:27 UTC
Labels: bug, trigger/poll
