### ISSUE TITLE
Templated Helm values not working

### ISSUE THREAD

**Issue by The-Loeki** [keel-hq/keel#294] opened 2018-10-19 10:16 UTC
Helm introduced the `tpl` function a few releases back.
This leads to the following interesting possibility:

`Chart.yaml`:
```yaml
appVersion: 1.7
```

`deployment.yaml`:
```yaml
      containers:
      - image: {{ .Values.image }}:{{ tpl .Values.imageTag . }}
```

`values.yaml`:
```yaml
image: anImageYesYes
imageTag: v{{ .Chart.AppVersion }}-alpine
```

Which leads to Keel bugging out like:
```
level=error msg="provider.helm: failed to parse image" error="Error parsing reference: \"example.com/etc/anImageYesYes:v{{ .Chart.AppVersion }}\" is not a valid repository/tag, error: invalid reference format" repository_name=image repository_tag=imageTag
```

**Comment by rusenask** [comment] 2018-10-19 10:30
updating Helm library dependencies in keel might do the job as we are using `"k8s.io/helm/pkg/chartutil"` to parse config. Could you create an example that I could use to reproduce and test against?

**Comment by The-Loeki** [comment] 2018-10-19 10:39
Sure! Here's a modified version of Traefik for example: https://gitlab.com/ors-it/oss/helm-traefik

**Comment by WesleyCharlesBlake** [comment] 2018-10-19 13:12
Can confirm the same behavior here:

```time="2018-10-19T13:05:13Z" level=error msg="provider.helm: failed to parse image" error="Error parsing reference: \"poetapp/node:v{{ .Chart.AppVersion }}\" is not a valid repository/tag, error: invalid reference format" repository_name=image.repository repository_tag=image.tag
```

Deployment template: 
```
...
          image: {{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}
...
```

When I do a dry run, I can confirm that helm is parsing the correct version inherited from the Chart.yaml:

Something to note though, is that the COMPUTED vals in helm show:

```
COMPUTED VALUES:
...
image:
  pullPolicy: IfNotPresent
  repository: poetapp/node
  tag: v{{ .Chart.AppVersion }}
...
```

But the manifests indicate the correctly parsed tag:

```
MANIFEST:
...
# Source: poet-node/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: test-tpl-ver-poet-node
  labels:
    app: poet-node
    chart: poet-node-1.0.6
    release: test-tpl-ver
    heritage: Tiller
spec:
  replicas: 1
  revisionHistoryLimit: 5
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: poet-node
      release: test-tpl-ver
  template:
    metadata:
      labels:
        app: poet-node
        release: test-tpl-ver
    spec:
      containers:
        - name: poet-node
          image: poetapp/node:v1.8.1
...
```

appending the `--dry-run --debug` args to the `helm install ..` command will give the above info which can help with trouble shooting as well

**Comment by The-Loeki** [comment] 2018-10-19 13:42
hadn't noticed that... But you're right, Helm itself is not clean on this either; the welcome messages contain the template string as well rather than the rendered version.

It might actually be an 'undocumented feature' of Helm then, and one which might be hard to fix too, as the `tpl` string must by definition be rendered within the context of where it's called, not where it's saved...

**Comment by WesleyCharlesBlake** [comment] 2018-11-05 09:34
@The-Loeki I tried some more approaches here, and one was to use something similar to how the keel helm chart deployment templates specifies the tags, and whilst it worked, it was not picking up deployments since the `.Values.image.tag` was not set in the values.yaml files. So it did not pick up the contect at runtime when needing to update.

Bit of a bummer because I have one helm chart with about 9 different deployments, and it would be really cool to have a better way to template the variables across.

Im not entirely sure this is an issue keel, but how Tiller handles the values passed in.

**Comment by rusenask** [comment] 2019-06-14 09:16
closing this due to age, basically Keel just passes some values to Tiller. This might be a non-issue with Helm v3.

**Closed by rusenask** 2019-06-14 09:16 UTC
Labels: bug, help wanted, provider/helm
