### ISSUE TITLE
Image pull secret not found

### ISSUE THREAD

**Issue by phertweck** [keel-hq/keel#293] opened 2018-10-18 07:06 UTC
Hello,

I deployed keel into kube-system namespace using the Helm chart. Unfortunately there seems to be a problem with recognizing the image pull secrets for my private docker registry.

```0-18T06:39:31Z" level=info msg="provider.kubernetes: using in-cluster configuration"

time="2018-10-18T06:39:31Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered"

time="2018-10-18T06:39:31Z" level=info msg="provider.defaultProviders: provider 'helm' registered"

time="2018-10-18T06:39:31Z" level=info msg="extension.credentialshelper: helper registered" name=secrets

time="2018-10-18T06:39:31Z" level=info msg="bot.slack.Configure(): Slack approval bot is not configured"

time="2018-10-18T06:39:31Z" level=error msg="bot.Run(): can not get configuration for bot [slack]"

time="2018-10-18T06:39:31Z" level=info msg="trigger.poll.manager: polling trigger configured"

time="2018-10-18T06:39:31Z" level=info msg=started context=watch resource=deployments

time="2018-10-18T06:39:31Z" level=info msg="webhook trigger server starting..." port=9300

time="2018-10-18T06:39:31Z" level=info msg=started context=watch resource=daemonsets

time="2018-10-18T06:39:31Z" level=info msg=started context=watch resource=cronjobs

time="2018-10-18T06:39:31Z" level=info msg=started context=watch resource=statefulsets

time="2018-10-18T06:39:31Z" level=info msg=started context=buffer

time="2018-10-18T06:39:31Z" level=error msg="provider.helm: failed to get config for release" error="policy not specified" namespace=cattle-system release=rancher

time="2018-10-18T06:39:33Z" level=info msg="trigger.poll.RepositoryWatcher: new watch tag digest job added" digest="sha256:654f02531de0f0bf7cc0a23eda8d4dc7a5be2a94634e48a2005d8d0398468c69" image="keelhq/keel:alpha" job_name="index.docker.io/keelhq/keel:alpha" schedule="@every 3m"

time="2018-10-18T06:39:36Z" level=error msg="provider.helm: failed to get config for release" error="policy not specified" namespace=cattle-system release=rancher

time="2018-10-18T06:39:36Z" level=warning msg="secrets.defaultGetter.lookupSecrets: docker credentials were not found among secrets" image="myPrivateDockerRegistry.com/my/image" namespace=dev provider=kubernetes registry="myPrivateDockerRegistry.com" secrets="[pullsecret1 pullsecret2]"

time="2018-10-18T06:39:37Z" level=error msg="trigger.poll.RepositoryWatcher.addJob: failed to get image digest" error="Get https://myPrivateDockerRegistry.com/v2/my/image/manifests/latest: http: non-successful response (status=401 body=\"{\\\"errors\\\":[{\\\"code\\\":\\\"UNAUTHORIZED\\\",\\\"message\\\":\\\"authentication required\\\",\\\"detail\\\":[{\\\"Type\\\":\\\"repository\\\",\\\"Class\\\":\\\"\\\",\\\"Name\\\":\\\"my/image\\\",\\\"Action\\\":\\\"pull\\\"}]}]}\\n\")" image="my/image:latest"```

But the pull secrets are available in the dev namespace:
`> kubectl get secrets -n dev
NAME                  TYPE                                  DATA      AGE
default-token-x7sgq   kubernetes.io/service-account-token   3         23h
pullsecret1           kubernetes.io/dockerconfigjson        1         23h
pullsecret2		      kubernetes.io/dockerconfigjson        1         23h`

I also tried to populate the secrets to the kube-system namespace without any success.

Is my configuration wrong? Thank you for your help!

**Comment by rusenask** [comment] 2018-10-18 10:36
hmm seems like it does find the secrets, what's the format of the secret contents?

**Comment by phertweck** [comment] 2018-10-18 13:13
Thank you for your fast response.

The secret looks like this:
```
> kubectl get secret pullsecret1 -n dev -o yaml
apiVersion: v1
data:
  .dockerconfigjson: XXXX
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: u-XXXX
    field.cattle.io/projectId: local:p-XXXX
    lifecycle.cattle.io/create.secretsController_local: "true"
    secret.user.cattle.io/secret: "true"
  creationTimestamp: 2018-10-17T07:20:55Z
  name: pullsecret1
  namespace: dev
  resourceVersion: "440873"
  selfLink: /api/v1/namespaces/dev/secrets/pullsecret1
  uid: 2fc2de33-d1dd-11e8-9605-9e47fcc86f23
type: kubernetes.io/dockerconfigjson
```

If I decode the .dockerconfigjson I get:
`{"auths":{"myPrivateDockerRegistry.com":{"password":"mySuperSecretpassword","username":"myuser"}}}`

**Comment by rusenask** [comment] 2018-10-18 13:48
are the secrets in the same namespace as the deployment?

**Comment by phertweck** [comment] 2018-10-18 13:59
Yes, both are in the same namespace.

**Comment by aleksey005** [comment] 2018-10-31 07:11
Hello, 

i use private docker hub and rancher 2, keel.sh 0.12.0 - enviroment variable 

`DOCKER_REGISTRY_CFG={"auths":{"https://index.docker.io/v1/":{"username":"login","password":"somepass","email":"email@email.com","auth":"longbase64secret"}}}`

not work.

Event
Warning | Failed | Failed to pull image "": rpc error: code = Unknown desc = Error response from daemon: pull access denied for , repository does not exist or may require 'docker login'

**Comment by aleksey005** [comment] 2018-11-01 08:05
Resolve. I use every node in claster

docker login docker.io
cp ~/.docker/config.json /var/lib/kubelet/

**Comment by rusenask** [comment] 2018-11-14 20:16
potential duplicate of https://github.com/keel-hq/keel/issues/306

**Closed by rusenask** 2018-11-14 20:16 UTC
