### ISSUE TITLE
Why Keel don't upgrade docker container if I deploy Keel at the end?

### ISSUE THREAD

**Issue by compozitor** [keel-hq/keel#259] opened 2018-08-30 09:03 UTC
At the begin I make a namespace "**develop**".
In this namespace I deploy all my containers.
At the end I deploy Keel. But Keel don't want upgrade my container "**mysql-nafta-update:0.0.1-dev**".
In the register there is a new image  "**mysql-nafta-update:0.0.2-dev**".
Tell me why?
```
time="2018-08-30T07:55:12Z" level=info msg="extension.notification: sender registered" name=hipchat,
time="2018-08-30T07:55:12Z" level=info msg="extension.notification: sender registered" name=mattermost,
time="2018-08-30T07:55:12Z" level=info msg="extension.notification: sender registered" name=slack,
time="2018-08-30T07:55:12Z" level=info msg="extension.notification: sender registered" name=webhook,
time="2018-08-30T07:55:12Z" level=info msg="extension.credentialshelper: helper registered" name=aws,
time="2018-08-30T07:55:12Z" level=info msg="bot: registered" name=slack,
time="2018-08-30T07:55:12Z" level=info msg="keel starting..." arch=amd64 build_date=2018-06-25T212350Z go_version=go1.10.3 os=linux revision=73b16284 version=0.9.5,
time="2018-08-30T07:55:12Z" level=info msg="provider.kubernetes: using in-cluster configuration",
time="2018-08-30T07:55:12Z" level=info msg="provider.defaultProviders: provider 'kubernetes' registered",
time="2018-08-30T07:55:12Z" level=info msg="extension.credentialshelper: helper registered" name=secrets,
time="2018-08-30T07:55:12Z" level=info msg="bot.slack.Configure(): Slack approval bot is not configured",
time="2018-08-30T07:55:12Z" level=error msg="bot.Run(): can not get configuration for bot [slack]",
time="2018-08-30T07:55:12Z" level=info msg=started context=buffer,
time="2018-08-30T07:55:12Z" level=info msg="trigger.poll.manager: polling trigger configured",
time="2018-08-30T07:55:12Z" level=info msg=started context=watch resource=statefulsets,
time="2018-08-30T07:55:12Z" level=info msg="webhook trigger server starting..." port=9300,
time="2018-08-30T07:55:12Z" level=info msg=started context=watch resource=deployments,
time="2018-08-30T07:55:12Z" level=info msg=started context=watch resource=daemonsets,
time="2018-08-30T07:55:19Z" level=info msg="trigger.poll.RepositoryWatcher: new watch repository tags job added" digest="sha256:51e7ca043beabda93f44665ad72cdd1029eb6cad9c18f5279a2985f931e13f9f" image="compozitor/mysql-nafta:0.0.1" job_name=registry.gitlab.com/compozitor/mysql-nafta schedule="@every 1m",
time="2018-08-30T07:55:20Z" level=info msg="trigger.poll.WatchRepositoryTagsJob: submiting event to providers" new_tag=0.0.3-dev repository=registry.gitlab.com/compozitor/mysql-nafta,
time="2018-08-30T07:55:20Z" level=info msg="provider.kubernetes: processing event" registry= repository=registry.gitlab.com/compozitor/mysql-nafta tag=0.0.3-dev,
time="2018-08-30T07:55:20Z" level=info msg="provider.kubernetes.checkVersionedDeployment: keel policy found, checking resource..." kind=deployment labels="map[app:server-nafta keel.sh/policy:all keel.sh/trigger:poll]" name=server-nafta-mysql namespace=default policy=all,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: checking image" image="registry.gitlab.com/compozitor/mysql-nafta:0.0.1" kind=deployment name=server-nafta-mysql namespace=default parsed_image_name="registry.gitlab.com/compozitor/mysql-nafta:0.0.1" policy=all target_image_name=registry.gitlab.com/compozitor/mysql-nafta target_tag=0.0.3-dev,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: current image version" current_version=0.0.1 image="registry.gitlab.com/compozitor/mysql-nafta:0.0.1" labels="map[app:server-nafta keel.sh/policy:all keel.sh/trigger:poll]" name=server-nafta-mysql namespace=default policy=all,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: checked version, deciding whether to update" current_version=0.0.1 image="registry.gitlab.com/compozitor/mysql-nafta:0.0.1" labels="map[app:server-nafta keel.sh/policy:all keel.sh/trigger:poll]" name=server-nafta-mysql namespace=default new_version=0.0.3-dev policy=all should_update=false,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes.checkVersionedDeployment: keel policy found, checking resource..." kind=deployment labels="map[keel.sh/policy:all keel.sh/trigger:poll app:update-nafta-mysql]" name=update-nafta-mysql namespace=default policy=all,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: checking image" image="registry.gitlab.com/compozitor/mysql-nafta-update:0.0.3" kind=deployment name=update-nafta-mysql namespace=default parsed_image_name="registry.gitlab.com/compozitor/mysql-nafta-update:0.0.3" policy=all target_image_name=registry.gitlab.com/compozitor/mysql-nafta target_tag=0.0.3-dev,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: images do not match, ignoring" parsed_image_name="registry.gitlab.com/compozitor/mysql-nafta-update:0.0.3" target_image_name=registry.gitlab.com/compozitor/mysql-nafta,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes.checkVersionedDeployment: keel policy found, checking resource..." kind=deployment labels="map[app:server-nafta-dev keel.sh/policy:all keel.sh/trigger:poll]" name=server-nafta-mysql-dev namespace=develop policy=all,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: checking image" image="registry.gitlab.com/compozitor/mysql-nafta:0.0.3-dev" kind=deployment name=server-nafta-mysql-dev namespace=develop parsed_image_name="registry.gitlab.com/compozitor/mysql-nafta:0.0.3-dev" policy=all target_image_name=registry.gitlab.com/compozitor/mysql-nafta target_tag=0.0.3-dev,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: current image version" current_version=0.0.3-dev image="registry.gitlab.com/compozitor/mysql-nafta:0.0.3-dev" labels="map[app:server-nafta-dev keel.sh/policy:all keel.sh/trigger:poll]" name=server-nafta-mysql-dev namespace=develop policy=all,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: checked version, deciding whether to update" current_version=0.0.3-dev image="registry.gitlab.com/compozitor/mysql-nafta:0.0.3-dev" labels="map[app:server-nafta-dev keel.sh/policy:all keel.sh/trigger:poll]" name=server-nafta-mysql-dev namespace=develop new_version=0.0.3-dev policy=all should_update=false,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes.checkVersionedDeployment: keel policy found, checking resource..." kind=deployment labels="map[app:update-nafta-mysql-dev keel.sh/policy:all keel.sh/trigger:poll]" name=update-nafta-mysql-dev namespace=develop policy=all,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: checking image" image="registry.gitlab.com/compozitor/mysql-nafta-update:0.0.1-dev" kind=deployment name=update-nafta-mysql-dev namespace=develop parsed_image_name="registry.gitlab.com/compozitor/mysql-nafta-update:0.0.1-dev" policy=all target_image_name=registry.gitlab.com/compozitor/mysql-nafta target_tag=0.0.3-dev,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: images do not match, ignoring" parsed_image_name="registry.gitlab.com/compozitor/mysql-nafta-update:0.0.1-dev" target_image_name=registry.gitlab.com/compozitor/mysql-nafta,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes.checkVersionedDeployment: keel policy found, checking resource..." kind=deployment labels="map[keel.sh/policy:all name:wd]" name=wd namespace=develop policy=all,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: checking image" image="karolisr/webhook-demo:0.0.2" kind=deployment name=wd namespace=develop parsed_image_name="index.docker.io/karolisr/webhook-demo:0.0.2" policy=all target_image_name=registry.gitlab.com/compozitor/mysql-nafta target_tag=0.0.3-dev,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: images do not match, ignoring" parsed_image_name="index.docker.io/karolisr/webhook-demo:0.0.2" target_image_name=registry.gitlab.com/compozitor/mysql-nafta,
time="2018-08-30T07:55:21Z" level=info msg="provider.kubernetes: no plans for deployment updates found for this event" image=registry.gitlab.com/compozitor/mysql-nafta tag=0.0.3-dev,
time="2018-08-30T07:55:22Z" level=info msg="trigger.poll.RepositoryWatcher: new watch repository tags job added" digest="sha256:4f28ee85228fda35973fe89acec48c36a9368304c67799daa5f3998a353b5ae5" image="compozitor/mysql-nafta-update:0.0.3" job_name=registry.gitlab.com/compozitor/mysql-nafta-update schedule="@every 1m",
```

**Comment by rusenask** [comment] 2018-08-30 09:26
Hi, duplicate of https://github.com/keel-hq/keel/issues/252, I think we should support this.

**Closed by rusenask** 2018-08-30 09:26 UTC

**Comment by compozitor** [comment] 2018-08-30 14:27
@rusenask If last container in repository have a version tag with additional metadata such as 3.0.0-dev but keel needs update container with tag without additional metadata such as 3.0.1 then update don't work. 

The reverse is also true.

If last container in repository have a version tag with additional metadata such as 3.0.0-dev and keel needs update container with tag with additional metadata such as 3.0.1-dev then update successfully. 

@rusenask Can you make that the keel does not stop on the last image in the repository, but looks for the appropriate last image with or without an additional tag, depending on the container being updated?

**Comment by rusenask** [comment] 2018-08-30 14:30
Do you mean if there are 1.5.0-dev and 1.6.0 available, keel won't upgrade your deployment if it's currently 1.0.0-dev?

Do I understand this correctly?

**Comment by compozitor** [comment] 2018-08-30 14:32
Yes

**Comment by compozitor** [comment] 2018-08-30 14:49
@rusenask Such a situation arises when the initial deploy. Then, if the required containers appear in the repository, everything is updated normally.
